services:
  flx-db:
    container_name: postgres_container
    hostname: 'flx-db-pg'
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres1:/var/lib/postgresql/data
      # the sql script to create table
      - ./packages/db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped

  flx-web-app:
    build: packages/web-app
    hostname: 'flx-web-app'
    depends_on:
      - 'flx-db'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: 'flx-db'
      POSTGRES_PORT: '5432'
    volumes:
      - ${FILE_ROOT_DIR}:${FILE_ROOT_DIR}
    ports:
      - '8282:8282'
    restart: unless-stopped

volumes:
  postgres1:

