FROM node:16.15-alpine

RUN mkdir -p /usr/src/app/ui
RUN mkdir -p /usr/src/app/back

ENV PATH /usr/src/app/node_modules/.bin:$PATH

WORKDIR /usr/src/app/ui
COPY ./packages/web-app-front /usr/src/app/ui
COPY ./packages/web-app-front /usr/src/app/ui
RUN npm ci
RUN npm build

WORKDIR /usr/src/app/ui


RUN npm i



#RUN npm run build

EXPOSE 8282

CMD ["npm", "start"]
